export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOG_OUT_USER";

export const CLEAR_ERROR_SUCCESS_STATE = "CLEAR_ERROR_SUCCESS_STATE";

export const ADD_USER = "ADD_USER";

export const SET_CATEGORY_FILTER = "SET_CATEGORY_FILTER";
export const SET_SORT_BY = "SET_SORT_BY";

export const ADD_DELIVERY_INFO = "ADD_DELIVERY_INFO";
export const EDIT_DELIVERY_INFO = "EDIT_DELIVERY_INFO";

export const SAVE_PAYMENT_INFO = "SAVE_PAYMENT_INFO";


export const CLEAR_CART = "CLEAR_CART";
// export const RESET_STORE = "RESET_STORE";
